### ISSUE TITLE
Extend supported labels and tasks

### ISSUE THREAD

**Issue by beat-buesser** [IBM/adversarial-robustness-toolbox#272]
Currently ART supports either one-hot encoded or index labels for categorical classification tasks.

We plan to extend ART to accept (ideally) all possible label formats. The following labels and tasks should be supported:

- [ ] object detection labels, image segmentation
- [ ] images / tensors as labels / autoencoder / VAE
- [ ] sequences as labels / seq2seq models
- [ ] regression tasks
- [ ] ...

**Comment by beat-buesser** [comment]
I will start investigating new/general label formats using branch ` development_labels ` to understand if this epic can be implemented in one issue or if it can be broken up into multiple issues.

**Comment by beat-buesser** [comment]
This issue will also solve #251

**Comment by beat-buesser** [comment]
I'm closing this epic because it has been replaced with multiple detailed epics which will provide a general solution: #308 #309 #310 #311
