### ISSUE TITLE
Create new Data API

### ISSUE THREAD

**Issue by beat-buesser** [IBM/adversarial-robustness-toolbox#310]
Supporting all possible machine learning tasks in addition to the current classification is facilitated by a new Data API. This Data API will become the preferred way of providing data to ART, while ART sill provide backward compatible support for ndarray-like objects. This new Data API will provide:

- [ ] a central implementations of dynamic data loading
- [ ] batching
- [ ] interfaces for data poisoning attacks, defences and detection
- [ ] data downloading
- [ ] datatype/task specific implementations, e.g. image classification, object detection, audio, video, text, etc.
- [ ] dataset-specific implementations for standard datasets
