### ISSUE TITLE
Adapt ART to feature vectors

### ISSUE THREAD

**Issue by ririnicolae** [IBM/adversarial-robustness-toolbox#49]
This requires multiple changes to all modules:

- [x] Allow `clip_values` to be `None` in all classifiers
- [x] Allow `clip_values` to have a different value per feature
- [ ] Similarly, change attack strength (often `eps`, `eps_step`) from just scalar to scalar or vector. If  a vector is provided, it should have the same size as the number of features. This is to allow attacks to be applied on features with different ranges and mostly concerns L_inf attacks.
- [ ] In line with the previous item, adapt random initialization in boundary attack to take into account the different scales in features for feature vectors.
- [x] Only perform clipping in attacks if the targeted model has `clip_values`
- [x] Generalize the shape of the input assumed in `Classifier` and other modules: moving from four dimensions (first one being the batch) to any number of dimensions (where first one is still the batch size)
- [x] Add checks and safeguards on number of dimensions of data for the attacks / defences that can only be applied on images
- [x] Add tests for feature vectors classifiers
- [x] Add tests with no clipping / clipping per feature for both images and feature vectors
- [ ] Update examples and notebooks to ensure that they still work
- [ ] Create notebook with attacks on feature vectors using some malware dataset

**Comment by ririnicolae** [comment]
I think this issue is ready to be closed. An example of usage for feature vectors is provided in PR #92. The item on having per-feature values for attack strenghts `eps` should probably be further discussed and addressed in a separate issue.
